### ISSUE TITLE
Fix the buggy script so it fills out the prompts correctly based on {topic} and fills out all sections

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/data-magic#1]
The script performs the first part correctly, which is to generate markdown `.md` files based on the parameters listed in `file_info.csv`.

But, it doesn't properly replace {Topic} with the `Topic` from `file_info.csv`.

It also doesn't fill out all the sections of the `template.md` with GPT content that is prompted by `prompts.yml`.

---

### What's supposed to happen

1) Page Title, File Name, and Topic (same as Page Title) are populated from `file_info.csv`

2) GPT Prompts are authored in `prompts.yml`

3) The content is generated into Markdown `.md` files based on the structure provided in `template.md`

**Comment by futuresoup** [comment]
Hi @howard989 - it's ready for you to try out. Any suggestions from others on the `Internet` also welcome.

**Comment by howard989** [comment]
resolved
