### ISSUE TITLE
Put app routes into api/routes.py

### ISSUE THREAD

**Issue by bigolboyyo** [climate-tech-handbook/data-magic#24]
To provide more DRY code, I will abstract the routes from `app.py` into `api/routes.py` and use the blueprints in the `app.py`

**Comment by shreeup** [comment]
I will take a look into this task.

**Comment by bigolboyyo** [comment]
> I will take a look into this task.

Very nice! Here's the Flask blueprint docs if needed: https://flask.palletsprojects.com/en/2.2.x/blueprints/
