### ISSUE TITLE
Update script to include pictures

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/data-magic#5]
Goal: make it as easy as possible to grab a cover photo from [Unsplash](unsplash.com) for each page, i.e. the [Solutions](climatetechhandbook.com/solutions) pages.

**Possible approach:**

- Content editor selects photos and populates a column for the URL and photo credit URL in a **.csv** file, similar to the way we set up `file_info.csv` in the [content-generator](https://github.com/climate-tech-handbook/data-magic) for authoring Markdown content.

**Ideal approach:**
- there is an automated keyword search from [Unsplash](unsplash.com) that grabs a suggested photo

**Challenges:**
- _list here_

**Comment by futuresoup** [comment]
@howard989 want to give it a shot? There are 93 solution pages that I'm going to start publishing this week.

It's not the end of the world to manually grab and update 93 photos if you think this will take up too much time to figure out or implement

**Comment by bigolboyyo** [comment]
We def have a few venues here. If you are going to manually upload then I would suggest just splitting up the work and generating unique AI images at least via, Dalle, midjourney, nightcafe, etc. That would at least make the work and effort of it something unique.

The other thing is we can make image requests ourselves with OpenAI it just costs a fraction of a cent. Our you could just write a quick loop and grab 50 unsplash images.

**Comment by howard989** [comment]
# https://github.com/climate-tech-handbook/data-magic/pull/12
