### ISSUE TITLE
Make content-generator sub-directory

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/data-magic#6]
@howard989 I was thinking that `content-generator` should be sub-directory of the root `data-magic` so that we can have several scripts for various automation tasks in a single repo.

Is there a reason you chose to delete that folder?

I'm not a programmer so it's possible there's a reason that I'm not aware of.

**Comment by howard989** [comment]
I did it by mistake, I was going to delete the original one and upload the new one, I forget to create the new content-generator folder, let me recreate the folder

**Comment by bigolboyyo** [comment]
Last night I created a flask app and set up directory structure here on my own fork.

https://github.com/bigolboyyo/data-magic-wg

Was going to work on the GPT modeling today for the requesting and formatting.

**Comment by futuresoup** [comment]
@howard989 no problem, all set!

@bigolboyyo can you make a new Issue for implementing up the flask app and describe the goal? Is it a way to make the *content-generator* more efficient?

**Comment by bigolboyyo** [comment]
Well as we progress we want an actual AI chat bot right? We also plan to do fine-tuning and train our models on the environmental data as well.

Having an app and creating a structured and organized codebase will help in a variety of ways. It'll allow devs to jump into the code and work on specific sections, without having to necessarily learn the whole code base. This goes for devs of all levels.

And allow us to be adaptable and scalable in our needs.
